// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaterSensorProto.proto

package com.SerIoTics.data_generation;

public final class SensorProtos {
  private SensorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WaterSensorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.SerIoTics.data_generation.WaterSensor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string minType = 1;</code>
     */
    boolean hasMinType();
    /**
     * <code>optional string minType = 1;</code>
     */
    java.lang.String getMinType();
    /**
     * <code>optional string minType = 1;</code>
     */
    com.google.protobuf.ByteString
        getMinTypeBytes();

    /**
     * <code>optional string majType = 2;</code>
     */
    boolean hasMajType();
    /**
     * <code>optional string majType = 2;</code>
     */
    java.lang.String getMajType();
    /**
     * <code>optional string majType = 2;</code>
     */
    com.google.protobuf.ByteString
        getMajTypeBytes();

    /**
     * <code>optional string item_sensed = 3;</code>
     */
    boolean hasItemSensed();
    /**
     * <code>optional string item_sensed = 3;</code>
     */
    java.lang.String getItemSensed();
    /**
     * <code>optional string item_sensed = 3;</code>
     */
    com.google.protobuf.ByteString
        getItemSensedBytes();

    /**
     * <code>optional string subject_measured = 4;</code>
     */
    boolean hasSubjectMeasured();
    /**
     * <code>optional string subject_measured = 4;</code>
     */
    java.lang.String getSubjectMeasured();
    /**
     * <code>optional string subject_measured = 4;</code>
     */
    com.google.protobuf.ByteString
        getSubjectMeasuredBytes();

    /**
     * <code>optional string sensor_location_name = 5;</code>
     */
    boolean hasSensorLocationName();
    /**
     * <code>optional string sensor_location_name = 5;</code>
     */
    java.lang.String getSensorLocationName();
    /**
     * <code>optional string sensor_location_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getSensorLocationNameBytes();

    /**
     * <code>optional int64 unique_id = 6;</code>
     */
    boolean hasUniqueId();
    /**
     * <code>optional int64 unique_id = 6;</code>
     */
    long getUniqueId();

    /**
     * <code>optional int64 runtime = 7;</code>
     */
    boolean hasRuntime();
    /**
     * <code>optional int64 runtime = 7;</code>
     */
    long getRuntime();

    /**
     * <code>optional float quantity = 8;</code>
     */
    boolean hasQuantity();
    /**
     * <code>optional float quantity = 8;</code>
     */
    float getQuantity();

    /**
     * <code>optional int32 major_area_num = 9;</code>
     */
    boolean hasMajorAreaNum();
    /**
     * <code>optional int32 major_area_num = 9;</code>
     */
    int getMajorAreaNum();

    /**
     * <code>optional int32 minor_area_num = 10;</code>
     */
    boolean hasMinorAreaNum();
    /**
     * <code>optional int32 minor_area_num = 10;</code>
     */
    int getMinorAreaNum();

    /**
     * <code>optional int32 time_since_turn_on = 11;</code>
     */
    boolean hasTimeSinceTurnOn();
    /**
     * <code>optional int32 time_since_turn_on = 11;</code>
     */
    int getTimeSinceTurnOn();
  }
  /**
   * Protobuf type {@code com.SerIoTics.data_generation.WaterSensor}
   */
  public static final class WaterSensor extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.SerIoTics.data_generation.WaterSensor)
      WaterSensorOrBuilder {
    // Use WaterSensor.newBuilder() to construct.
    private WaterSensor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WaterSensor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WaterSensor defaultInstance;
    public static WaterSensor getDefaultInstance() {
      return defaultInstance;
    }

    public WaterSensor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WaterSensor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              minType_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              majType_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              itemSensed_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              subjectMeasured_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              sensorLocationName_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              uniqueId_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              runtime_ = input.readInt64();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              quantity_ = input.readFloat();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              majorAreaNum_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              minorAreaNum_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              timeSinceTurnOn_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.SerIoTics.data_generation.SensorProtos.internal_static_com_SerIoTics_data_generation_WaterSensor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.SerIoTics.data_generation.SensorProtos.internal_static_com_SerIoTics_data_generation_WaterSensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.SerIoTics.data_generation.SensorProtos.WaterSensor.class, com.SerIoTics.data_generation.SensorProtos.WaterSensor.Builder.class);
    }

    public static com.google.protobuf.Parser<WaterSensor> PARSER =
        new com.google.protobuf.AbstractParser<WaterSensor>() {
      public WaterSensor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WaterSensor(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WaterSensor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MINTYPE_FIELD_NUMBER = 1;
    private java.lang.Object minType_;
    /**
     * <code>optional string minType = 1;</code>
     */
    public boolean hasMinType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string minType = 1;</code>
     */
    public java.lang.String getMinType() {
      java.lang.Object ref = minType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          minType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string minType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMinTypeBytes() {
      java.lang.Object ref = minType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAJTYPE_FIELD_NUMBER = 2;
    private java.lang.Object majType_;
    /**
     * <code>optional string majType = 2;</code>
     */
    public boolean hasMajType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string majType = 2;</code>
     */
    public java.lang.String getMajType() {
      java.lang.Object ref = majType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          majType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string majType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMajTypeBytes() {
      java.lang.Object ref = majType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        majType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEM_SENSED_FIELD_NUMBER = 3;
    private java.lang.Object itemSensed_;
    /**
     * <code>optional string item_sensed = 3;</code>
     */
    public boolean hasItemSensed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string item_sensed = 3;</code>
     */
    public java.lang.String getItemSensed() {
      java.lang.Object ref = itemSensed_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemSensed_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string item_sensed = 3;</code>
     */
    public com.google.protobuf.ByteString
        getItemSensedBytes() {
      java.lang.Object ref = itemSensed_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemSensed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_MEASURED_FIELD_NUMBER = 4;
    private java.lang.Object subjectMeasured_;
    /**
     * <code>optional string subject_measured = 4;</code>
     */
    public boolean hasSubjectMeasured() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string subject_measured = 4;</code>
     */
    public java.lang.String getSubjectMeasured() {
      java.lang.Object ref = subjectMeasured_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subjectMeasured_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subject_measured = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectMeasuredBytes() {
      java.lang.Object ref = subjectMeasured_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectMeasured_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSOR_LOCATION_NAME_FIELD_NUMBER = 5;
    private java.lang.Object sensorLocationName_;
    /**
     * <code>optional string sensor_location_name = 5;</code>
     */
    public boolean hasSensorLocationName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string sensor_location_name = 5;</code>
     */
    public java.lang.String getSensorLocationName() {
      java.lang.Object ref = sensorLocationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sensorLocationName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sensor_location_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSensorLocationNameBytes() {
      java.lang.Object ref = sensorLocationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorLocationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIQUE_ID_FIELD_NUMBER = 6;
    private long uniqueId_;
    /**
     * <code>optional int64 unique_id = 6;</code>
     */
    public boolean hasUniqueId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 unique_id = 6;</code>
     */
    public long getUniqueId() {
      return uniqueId_;
    }

    public static final int RUNTIME_FIELD_NUMBER = 7;
    private long runtime_;
    /**
     * <code>optional int64 runtime = 7;</code>
     */
    public boolean hasRuntime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 runtime = 7;</code>
     */
    public long getRuntime() {
      return runtime_;
    }

    public static final int QUANTITY_FIELD_NUMBER = 8;
    private float quantity_;
    /**
     * <code>optional float quantity = 8;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional float quantity = 8;</code>
     */
    public float getQuantity() {
      return quantity_;
    }

    public static final int MAJOR_AREA_NUM_FIELD_NUMBER = 9;
    private int majorAreaNum_;
    /**
     * <code>optional int32 major_area_num = 9;</code>
     */
    public boolean hasMajorAreaNum() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 major_area_num = 9;</code>
     */
    public int getMajorAreaNum() {
      return majorAreaNum_;
    }

    public static final int MINOR_AREA_NUM_FIELD_NUMBER = 10;
    private int minorAreaNum_;
    /**
     * <code>optional int32 minor_area_num = 10;</code>
     */
    public boolean hasMinorAreaNum() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 minor_area_num = 10;</code>
     */
    public int getMinorAreaNum() {
      return minorAreaNum_;
    }

    public static final int TIME_SINCE_TURN_ON_FIELD_NUMBER = 11;
    private int timeSinceTurnOn_;
    /**
     * <code>optional int32 time_since_turn_on = 11;</code>
     */
    public boolean hasTimeSinceTurnOn() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 time_since_turn_on = 11;</code>
     */
    public int getTimeSinceTurnOn() {
      return timeSinceTurnOn_;
    }

    private void initFields() {
      minType_ = "";
      majType_ = "";
      itemSensed_ = "";
      subjectMeasured_ = "";
      sensorLocationName_ = "";
      uniqueId_ = 0L;
      runtime_ = 0L;
      quantity_ = 0F;
      majorAreaNum_ = 0;
      minorAreaNum_ = 0;
      timeSinceTurnOn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMinTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMajTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getItemSensedBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSubjectMeasuredBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSensorLocationNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, uniqueId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, runtime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, quantity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, majorAreaNum_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, minorAreaNum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, timeSinceTurnOn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMinTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMajTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getItemSensedBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSubjectMeasuredBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSensorLocationNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, uniqueId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, runtime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, quantity_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, majorAreaNum_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, minorAreaNum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, timeSinceTurnOn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.SerIoTics.data_generation.SensorProtos.WaterSensor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.SerIoTics.data_generation.SensorProtos.WaterSensor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.SerIoTics.data_generation.WaterSensor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.SerIoTics.data_generation.WaterSensor)
        com.SerIoTics.data_generation.SensorProtos.WaterSensorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.SerIoTics.data_generation.SensorProtos.internal_static_com_SerIoTics_data_generation_WaterSensor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.SerIoTics.data_generation.SensorProtos.internal_static_com_SerIoTics_data_generation_WaterSensor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.SerIoTics.data_generation.SensorProtos.WaterSensor.class, com.SerIoTics.data_generation.SensorProtos.WaterSensor.Builder.class);
      }

      // Construct using com.SerIoTics.data_generation.SensorProtos.WaterSensor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        minType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        majType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        itemSensed_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        subjectMeasured_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sensorLocationName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        uniqueId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        runtime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        quantity_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        majorAreaNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        minorAreaNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        timeSinceTurnOn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.SerIoTics.data_generation.SensorProtos.internal_static_com_SerIoTics_data_generation_WaterSensor_descriptor;
      }

      public com.SerIoTics.data_generation.SensorProtos.WaterSensor getDefaultInstanceForType() {
        return com.SerIoTics.data_generation.SensorProtos.WaterSensor.getDefaultInstance();
      }

      public com.SerIoTics.data_generation.SensorProtos.WaterSensor build() {
        com.SerIoTics.data_generation.SensorProtos.WaterSensor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.SerIoTics.data_generation.SensorProtos.WaterSensor buildPartial() {
        com.SerIoTics.data_generation.SensorProtos.WaterSensor result = new com.SerIoTics.data_generation.SensorProtos.WaterSensor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.minType_ = minType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.majType_ = majType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.itemSensed_ = itemSensed_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.subjectMeasured_ = subjectMeasured_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sensorLocationName_ = sensorLocationName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uniqueId_ = uniqueId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.runtime_ = runtime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.majorAreaNum_ = majorAreaNum_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.minorAreaNum_ = minorAreaNum_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.timeSinceTurnOn_ = timeSinceTurnOn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.SerIoTics.data_generation.SensorProtos.WaterSensor) {
          return mergeFrom((com.SerIoTics.data_generation.SensorProtos.WaterSensor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.SerIoTics.data_generation.SensorProtos.WaterSensor other) {
        if (other == com.SerIoTics.data_generation.SensorProtos.WaterSensor.getDefaultInstance()) return this;
        if (other.hasMinType()) {
          bitField0_ |= 0x00000001;
          minType_ = other.minType_;
          onChanged();
        }
        if (other.hasMajType()) {
          bitField0_ |= 0x00000002;
          majType_ = other.majType_;
          onChanged();
        }
        if (other.hasItemSensed()) {
          bitField0_ |= 0x00000004;
          itemSensed_ = other.itemSensed_;
          onChanged();
        }
        if (other.hasSubjectMeasured()) {
          bitField0_ |= 0x00000008;
          subjectMeasured_ = other.subjectMeasured_;
          onChanged();
        }
        if (other.hasSensorLocationName()) {
          bitField0_ |= 0x00000010;
          sensorLocationName_ = other.sensorLocationName_;
          onChanged();
        }
        if (other.hasUniqueId()) {
          setUniqueId(other.getUniqueId());
        }
        if (other.hasRuntime()) {
          setRuntime(other.getRuntime());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasMajorAreaNum()) {
          setMajorAreaNum(other.getMajorAreaNum());
        }
        if (other.hasMinorAreaNum()) {
          setMinorAreaNum(other.getMinorAreaNum());
        }
        if (other.hasTimeSinceTurnOn()) {
          setTimeSinceTurnOn(other.getTimeSinceTurnOn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.SerIoTics.data_generation.SensorProtos.WaterSensor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.SerIoTics.data_generation.SensorProtos.WaterSensor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object minType_ = "";
      /**
       * <code>optional string minType = 1;</code>
       */
      public boolean hasMinType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string minType = 1;</code>
       */
      public java.lang.String getMinType() {
        java.lang.Object ref = minType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            minType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string minType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMinTypeBytes() {
        java.lang.Object ref = minType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          minType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string minType = 1;</code>
       */
      public Builder setMinType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        minType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string minType = 1;</code>
       */
      public Builder clearMinType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minType_ = getDefaultInstance().getMinType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string minType = 1;</code>
       */
      public Builder setMinTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        minType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object majType_ = "";
      /**
       * <code>optional string majType = 2;</code>
       */
      public boolean hasMajType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string majType = 2;</code>
       */
      public java.lang.String getMajType() {
        java.lang.Object ref = majType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            majType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string majType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMajTypeBytes() {
        java.lang.Object ref = majType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          majType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string majType = 2;</code>
       */
      public Builder setMajType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        majType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string majType = 2;</code>
       */
      public Builder clearMajType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        majType_ = getDefaultInstance().getMajType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string majType = 2;</code>
       */
      public Builder setMajTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        majType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object itemSensed_ = "";
      /**
       * <code>optional string item_sensed = 3;</code>
       */
      public boolean hasItemSensed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string item_sensed = 3;</code>
       */
      public java.lang.String getItemSensed() {
        java.lang.Object ref = itemSensed_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            itemSensed_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string item_sensed = 3;</code>
       */
      public com.google.protobuf.ByteString
          getItemSensedBytes() {
        java.lang.Object ref = itemSensed_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemSensed_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string item_sensed = 3;</code>
       */
      public Builder setItemSensed(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        itemSensed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_sensed = 3;</code>
       */
      public Builder clearItemSensed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        itemSensed_ = getDefaultInstance().getItemSensed();
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_sensed = 3;</code>
       */
      public Builder setItemSensedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        itemSensed_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subjectMeasured_ = "";
      /**
       * <code>optional string subject_measured = 4;</code>
       */
      public boolean hasSubjectMeasured() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string subject_measured = 4;</code>
       */
      public java.lang.String getSubjectMeasured() {
        java.lang.Object ref = subjectMeasured_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            subjectMeasured_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subject_measured = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectMeasuredBytes() {
        java.lang.Object ref = subjectMeasured_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subjectMeasured_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subject_measured = 4;</code>
       */
      public Builder setSubjectMeasured(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        subjectMeasured_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject_measured = 4;</code>
       */
      public Builder clearSubjectMeasured() {
        bitField0_ = (bitField0_ & ~0x00000008);
        subjectMeasured_ = getDefaultInstance().getSubjectMeasured();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subject_measured = 4;</code>
       */
      public Builder setSubjectMeasuredBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        subjectMeasured_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sensorLocationName_ = "";
      /**
       * <code>optional string sensor_location_name = 5;</code>
       */
      public boolean hasSensorLocationName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sensor_location_name = 5;</code>
       */
      public java.lang.String getSensorLocationName() {
        java.lang.Object ref = sensorLocationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sensorLocationName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sensor_location_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSensorLocationNameBytes() {
        java.lang.Object ref = sensorLocationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensorLocationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sensor_location_name = 5;</code>
       */
      public Builder setSensorLocationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sensorLocationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sensor_location_name = 5;</code>
       */
      public Builder clearSensorLocationName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sensorLocationName_ = getDefaultInstance().getSensorLocationName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sensor_location_name = 5;</code>
       */
      public Builder setSensorLocationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sensorLocationName_ = value;
        onChanged();
        return this;
      }

      private long uniqueId_ ;
      /**
       * <code>optional int64 unique_id = 6;</code>
       */
      public boolean hasUniqueId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 unique_id = 6;</code>
       */
      public long getUniqueId() {
        return uniqueId_;
      }
      /**
       * <code>optional int64 unique_id = 6;</code>
       */
      public Builder setUniqueId(long value) {
        bitField0_ |= 0x00000020;
        uniqueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 unique_id = 6;</code>
       */
      public Builder clearUniqueId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uniqueId_ = 0L;
        onChanged();
        return this;
      }

      private long runtime_ ;
      /**
       * <code>optional int64 runtime = 7;</code>
       */
      public boolean hasRuntime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 runtime = 7;</code>
       */
      public long getRuntime() {
        return runtime_;
      }
      /**
       * <code>optional int64 runtime = 7;</code>
       */
      public Builder setRuntime(long value) {
        bitField0_ |= 0x00000040;
        runtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 runtime = 7;</code>
       */
      public Builder clearRuntime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        runtime_ = 0L;
        onChanged();
        return this;
      }

      private float quantity_ ;
      /**
       * <code>optional float quantity = 8;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional float quantity = 8;</code>
       */
      public float getQuantity() {
        return quantity_;
      }
      /**
       * <code>optional float quantity = 8;</code>
       */
      public Builder setQuantity(float value) {
        bitField0_ |= 0x00000080;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float quantity = 8;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000080);
        quantity_ = 0F;
        onChanged();
        return this;
      }

      private int majorAreaNum_ ;
      /**
       * <code>optional int32 major_area_num = 9;</code>
       */
      public boolean hasMajorAreaNum() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 major_area_num = 9;</code>
       */
      public int getMajorAreaNum() {
        return majorAreaNum_;
      }
      /**
       * <code>optional int32 major_area_num = 9;</code>
       */
      public Builder setMajorAreaNum(int value) {
        bitField0_ |= 0x00000100;
        majorAreaNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 major_area_num = 9;</code>
       */
      public Builder clearMajorAreaNum() {
        bitField0_ = (bitField0_ & ~0x00000100);
        majorAreaNum_ = 0;
        onChanged();
        return this;
      }

      private int minorAreaNum_ ;
      /**
       * <code>optional int32 minor_area_num = 10;</code>
       */
      public boolean hasMinorAreaNum() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 minor_area_num = 10;</code>
       */
      public int getMinorAreaNum() {
        return minorAreaNum_;
      }
      /**
       * <code>optional int32 minor_area_num = 10;</code>
       */
      public Builder setMinorAreaNum(int value) {
        bitField0_ |= 0x00000200;
        minorAreaNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 minor_area_num = 10;</code>
       */
      public Builder clearMinorAreaNum() {
        bitField0_ = (bitField0_ & ~0x00000200);
        minorAreaNum_ = 0;
        onChanged();
        return this;
      }

      private int timeSinceTurnOn_ ;
      /**
       * <code>optional int32 time_since_turn_on = 11;</code>
       */
      public boolean hasTimeSinceTurnOn() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 time_since_turn_on = 11;</code>
       */
      public int getTimeSinceTurnOn() {
        return timeSinceTurnOn_;
      }
      /**
       * <code>optional int32 time_since_turn_on = 11;</code>
       */
      public Builder setTimeSinceTurnOn(int value) {
        bitField0_ |= 0x00000400;
        timeSinceTurnOn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time_since_turn_on = 11;</code>
       */
      public Builder clearTimeSinceTurnOn() {
        bitField0_ = (bitField0_ & ~0x00000400);
        timeSinceTurnOn_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.SerIoTics.data_generation.WaterSensor)
    }

    static {
      defaultInstance = new WaterSensor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.SerIoTics.data_generation.WaterSensor)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_SerIoTics_data_generation_WaterSensor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_SerIoTics_data_generation_WaterSensor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026WaterSensorProto.proto\022\035com.SerIoTics." +
      "data_generation\"\376\001\n\013WaterSensor\022\017\n\007minTy" +
      "pe\030\001 \001(\t\022\017\n\007majType\030\002 \001(\t\022\023\n\013item_sensed" +
      "\030\003 \001(\t\022\030\n\020subject_measured\030\004 \001(\t\022\034\n\024sens" +
      "or_location_name\030\005 \001(\t\022\021\n\tunique_id\030\006 \001(" +
      "\003\022\017\n\007runtime\030\007 \001(\003\022\020\n\010quantity\030\010 \001(\002\022\026\n\016" +
      "major_area_num\030\t \001(\005\022\026\n\016minor_area_num\030\n" +
      " \001(\005\022\032\n\022time_since_turn_on\030\013 \001(\005B-\n\035com." +
      "SerIoTics.data_generationB\014SensorProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_SerIoTics_data_generation_WaterSensor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_SerIoTics_data_generation_WaterSensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_SerIoTics_data_generation_WaterSensor_descriptor,
        new java.lang.String[] { "MinType", "MajType", "ItemSensed", "SubjectMeasured", "SensorLocationName", "UniqueId", "Runtime", "Quantity", "MajorAreaNum", "MinorAreaNum", "TimeSinceTurnOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
